include_guard(GLOBAL)

include(ExternalProject)

# player-lib: pass absolute CMAKE_TOOLCHAIN_FILE.
set(_player_lib_cmake_toolchain_args "")
if(CMAKE_TOOLCHAIN_FILE)
  get_filename_component(
    _player_lib_toolchain_abs "${CMAKE_TOOLCHAIN_FILE}" ABSOLUTE
  )
  list(
    APPEND _player_lib_cmake_toolchain_args
    "-DCMAKE_TOOLCHAIN_FILE=${_player_lib_toolchain_abs}"
  )
endif()

string(
  CONCAT _player_patch_cmd "git reset --hard HEAD && git clean -fd && "
         "patch -p1 --batch < \"" "${CMAKE_CURRENT_LIST_DIR}/player.patch" "\""
)

ExternalProject_Add(
  player-lib
  GIT_REPOSITORY https://github.com/playerproject/player.git
  GIT_TAG master
  PATCH_COMMAND bash -c "${_player_patch_cmd}"
  BUILD_BYPRODUCTS
    "${CMAKE_CURRENT_BINARY_DIR}/player_external/lib/libplayerc++.a"
    "${CMAKE_CURRENT_BINARY_DIR}/player_external/lib/libplayerc.a"
    "${CMAKE_CURRENT_BINARY_DIR}/player_external/lib/libplayerinterface.a"
    "${CMAKE_CURRENT_BINARY_DIR}/player_external/lib/libplayercommon.a"
    "${CMAKE_CURRENT_BINARY_DIR}/player_external/lib/libplayerwkb.a"
  CMAKE_ARGS
    ${_player_lib_cmake_toolchain_args}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}/player_external
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_EXAMPLES=OFF
    -DINCLUDE_RTK=OFF
    -DINCLUDE_RTKGUI=OFF
    -DPLAYER_BUILD_TESTS=OFF
    -DBUILD_PLAYERCC=ON
    -DBUILD_PLAYERCC_BOOST=OFF
    -DBUILD_PYTHONC_BINDINGS=OFF
    -DBUILD_UTILS=OFF
    -DENABLE_DRIVER_ACCEL_CALIB=OFF
    -DENABLE_DRIVER_ACR120U=OFF
    -DENABLE_DRIVER_ACTS=OFF
    -DENABLE_DRIVER_AIOTOSONAR=OFF
    -DENABLE_DRIVER_ALSA=OFF
    -DENABLE_DRIVER_AMCL=OFF
    -DENABLE_DRIVER_AMTECM5=OFF
    -DENABLE_DRIVER_AMTECPOWERCUBE=OFF
    -DENABLE_DRIVER_AODV=OFF
    -DENABLE_DRIVER_ARTOOLKITPLUS=OFF
    -DENABLE_DRIVER_BITLOGIC=OFF
    -DENABLE_DRIVER_BLOBPOSITION=OFF
    -DENABLE_DRIVER_BLOBTODIO=OFF
    -DENABLE_DRIVER_BLOBTRACKER=OFF
    -DENABLE_DRIVER_BUMPER2LASER=OFF
    -DENABLE_DRIVER_BUMPERSAFE=OFF
    -DENABLE_DRIVER_BUMPERTODIO=OFF
    -DENABLE_DRIVER_CAMERA1394=OFF
    -DENABLE_DRIVER_CAMERACOMPRESS=OFF
    -DENABLE_DRIVER_CAMERAGST=OFF
    -DENABLE_DRIVER_CAMERAREQ=OFF
    -DENABLE_DRIVER_CAMERAUNCOMPRESS=OFF
    -DENABLE_DRIVER_CAMERAUVC=OFF
    -DENABLE_DRIVER_CAMERAV4L=OFF
    -DENABLE_DRIVER_CAMERAV4L2=OFF
    -DENABLE_DRIVER_CAMFILTER=OFF
    -DENABLE_DRIVER_CANONVCC4=OFF
    -DENABLE_DRIVER_CLODBUSTER=OFF
    -DENABLE_DRIVER_CMDSPLITTER=OFF
    -DENABLE_DRIVER_CMUCAM2=OFF
    -DENABLE_DRIVER_CMVISION=OFF
    -DENABLE_DRIVER_CREATE=OFF
    -DENABLE_DRIVER_CVCAM=OFF
    -DENABLE_DRIVER_DEADSTOP=OFF
    -DENABLE_DRIVER_DIFFERENTIAL=OFF
    -DENABLE_DRIVER_DIOCMD=OFF
    -DENABLE_DRIVER_DIODELAY=OFF
    -DENABLE_DRIVER_DIOLATCH=OFF
    -DENABLE_DRIVER_DUMMY=OFF
    -DENABLE_DRIVER_EEDHCONTROLLER=OFF
    -DENABLE_DRIVER_EKFVLOC=OFF
    -DENABLE_DRIVER_EPUCK=OFF
    -DENABLE_DRIVER_ER1=OFF
    -DENABLE_DRIVER_ERRATIC=OFF
    -DENABLE_DRIVER_FAKELOCALIZE=OFF
    -DENABLE_DRIVER_FESTIVAL=OFF
    -DENABLE_DRIVER_FLEXIPORT=OFF
    -DENABLE_DRIVER_FLOCKOFBIRDS=OFF
    -DENABLE_DRIVER_GARCIA=OFF
    -DENABLE_DRIVER_GARMINNMEA=OFF
    -DENABLE_DRIVER_GBXGARMINACFR=OFF
    -DENABLE_DRIVER_GBXSICKACFR=OFF
    -DENABLE_DRIVER_GLOBALIZE=OFF
    -DENABLE_DRIVER_GOTO=OFF
    -DENABLE_DRIVER_GRIDMAP=OFF
    -DENABLE_DRIVER_GRIPCMD=OFF
    -DENABLE_DRIVER_GUILE=OFF
    -DENABLE_DRIVER_HEMISSON=OFF
    -DENABLE_DRIVER_HOKUYOAIST=OFF
    -DENABLE_DRIVER_IMAGESEQ=OFF
    -DENABLE_DRIVER_IMGCMP=OFF
    -DENABLE_DRIVER_IMGSAVE=OFF
    -DENABLE_DRIVER_INHIBITOR=OFF
    -DENABLE_DRIVER_INSIDEM300=OFF
    -DENABLE_DRIVER_ISENSE=OFF
    -DENABLE_DRIVER_IWSPY=OFF
    -DENABLE_DRIVER_KARTOWRITER=OFF
    -DENABLE_DRIVER_KHEPERA=OFF
    -DENABLE_DRIVER_KINECT=OFF
    -DENABLE_DRIVER_LASERBAR=OFF
    -DENABLE_DRIVER_LASERBARCODE=OFF
    -DENABLE_DRIVER_LASERCSPACE=OFF
    -DENABLE_DRIVER_LASERCUTTER=OFF
    -DENABLE_DRIVER_LASERFEATURE=OFF
    -DENABLE_DRIVER_LASERPOSEINTERPOLATOR=OFF
    -DENABLE_DRIVER_LASERPTZCLOUD=OFF
    -DENABLE_DRIVER_LASERRESCAN=OFF
    -DENABLE_DRIVER_LASERSAFE=OFF
    -DENABLE_DRIVER_LASERTORANGER=OFF
    -DENABLE_DRIVER_LASERVISUALBARCODE=OFF
    -DENABLE_DRIVER_LASERVISUALBW=OFF
    -DENABLE_DRIVER_LIBV4L2=OFF
    -DENABLE_DRIVER_LINUXJOYSTICK=OFF
    -DENABLE_DRIVER_LINUXWIFI=OFF
    -DENABLE_DRIVER_LOCALBB=OFF
    -DENABLE_DRIVER_MAPCSPACE=OFF
    -DENABLE_DRIVER_MAPFILE=OFF
    -DENABLE_DRIVER_MAPSCALE=OFF
    -DENABLE_DRIVER_MBASEDRIVER=OFF
    -DENABLE_DRIVER_MBICP=OFF
    -DENABLE_DRIVER_MICA2=OFF
    -DENABLE_DRIVER_MICROSTRAIN=OFF
    -DENABLE_DRIVER_MOTIONMIND=OFF
    -DENABLE_DRIVER_MRICP=OFF
    -DENABLE_DRIVER_ND=OFF
    -DENABLE_DRIVER_NIMU=OFF
    -DENABLE_DRIVER_NOMAD=OFF
    -DENABLE_DRIVER_NXT=OFF
    -DENABLE_DRIVER_OBOT=OFF
    -DENABLE_DRIVER_OCEANSERVER=OFF
    -DENABLE_DRIVER_OPAQUECMD=OFF
    -DENABLE_DRIVER_P2OS=OFF
    -DENABLE_DRIVER_PASSTHROUGH=OFF
    -DENABLE_DRIVER_PBSLASER=OFF
    -DENABLE_DRIVER_PHIDGETACC=OFF
    -DENABLE_DRIVER_PHIDGETIFK=OFF
    -DENABLE_DRIVER_PORTIO=OFF
    -DENABLE_DRIVER_POSTGIS=OFF
    -DENABLE_DRIVER_POSTLOG=OFF
    -DENABLE_DRIVER_POWERSHOT=OFF
    -DENABLE_DRIVER_PTU46=OFF
    -DENABLE_DRIVER_RANGERPOSEINTERPOLATOR=OFF
    -DENABLE_DRIVER_RANGERTODIO=OFF
    -DENABLE_DRIVER_RANGERTOLASER=OFF
    -DENABLE_DRIVER_RAZORIMU=OFF
    -DENABLE_DRIVER_RCORE_XBRIDGE=OFF
    -DENABLE_DRIVER_READLOG=OFF
    -DENABLE_DRIVER_REB=OFF
    -DENABLE_DRIVER_RELAY=OFF
    -DENABLE_DRIVER_RFLEX=OFF
    -DENABLE_DRIVER_ROBOTEQ=OFF
    -DENABLE_DRIVER_ROBOTINO=OFF
    -DENABLE_DRIVER_ROBOTRACKER=OFF
    -DENABLE_DRIVER_ROOMBA=OFF
    -DENABLE_DRIVER_RS4LEUZE=OFF
    -DENABLE_DRIVER_RT3XXX=OFF
    -DENABLE_DRIVER_SEARCHPATTERN=OFF
    -DENABLE_DRIVER_SEGWAYRMP=OFF
    -DENABLE_DRIVER_SEGWAYRMP400=OFF
    -DENABLE_DRIVER_SERIALSTREAM=OFF
    -DENABLE_DRIVER_SERIO=OFF
    -DENABLE_DRIVER_SERVICE_ADV_MDNS=OFF
    -DENABLE_DRIVER_SHAPETRACKER=OFF
    -DENABLE_DRIVER_SICKLDMRS=OFF
    -DENABLE_DRIVER_SICKLMS200=OFF
    -DENABLE_DRIVER_SICKLMS400=OFF
    -DENABLE_DRIVER_SICKNAV200=OFF
    -DENABLE_DRIVER_SICKRFI341=OFF
    -DENABLE_DRIVER_SICKS3000=OFF
    -DENABLE_DRIVER_SIMPLESHAPE=OFF
    -DENABLE_DRIVER_SKYETEKM1=OFF
    -DENABLE_DRIVER_SND=OFF
    -DENABLE_DRIVER_SONARTORANGER=OFF
    -DENABLE_DRIVER_SONYEVID30=OFF
    -DENABLE_DRIVER_SPEECHCMD=OFF
    -DENABLE_DRIVER_SPHERE=OFF
    -DENABLE_DRIVER_SPHEREPTZ=OFF
    -DENABLE_DRIVER_SPHINX2=OFF
    -DENABLE_DRIVER_SR3000=OFF
    -DENABLE_DRIVER_STALLTODIO=OFF
    -DENABLE_DRIVER_STATGRAB=OFF
    -DENABLE_DRIVER_STOC=OFF
    -DENABLE_DRIVER_SUPPRESSOR=OFF
    -DENABLE_DRIVER_SWISSRANGER=OFF
    -DENABLE_DRIVER_TCPSTREAM=OFF
    -DENABLE_DRIVER_UNICAPIMAGE=OFF
    -DENABLE_DRIVER_UPCBARCODE=OFF
    -DENABLE_DRIVER_VEC2MAP=OFF
    -DENABLE_DRIVER_VELCMD=OFF
    -DENABLE_DRIVER_VFH=OFF
    -DENABLE_DRIVER_VIDEOCANNY=OFF
    -DENABLE_DRIVER_VMAPFILE=OFF
    -DENABLE_DRIVER_WAVEFRONT=OFF
    -DENABLE_DRIVER_WBR914=OFF
    -DENABLE_DRIVER_WLANSCAN=OFF
    -DENABLE_DRIVER_WRITELOG=OFF
    -DENABLE_DRIVER_XSENSMT=OFF
    -DENABLE_DRIVER_YARPIMAGE=OFF
)

set(XIAOMI_PLAYER_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/player_external")
set(XIAOMI_PLAYER_LIB_DIR "${XIAOMI_PLAYER_PREFIX}/lib")
set(XIAOMI_PLAYER_CMAKE_MODULE_DIR
    "${XIAOMI_PLAYER_PREFIX}/share/cmake/Modules" CACHE PATH
    "Player CMake modules (UsePlayerC); optional CMAKE_MODULE_PATH entry"
)

# Static archives from `cmake --install` (BUILD_SHARED_LIBS=OFF on player-lib).
# Skip libplayerjpeg: needs HAVE_JPEG (often unset in cross/sysroot builds).
set(XIAOMI_PLAYER_STATIC_C
    "${XIAOMI_PLAYER_LIB_DIR}/libplayerc.a"
    "${XIAOMI_PLAYER_LIB_DIR}/libplayerinterface.a"
    "${XIAOMI_PLAYER_LIB_DIR}/libplayercommon.a"
    "${XIAOMI_PLAYER_LIB_DIR}/libplayerwkb.a"
)
set(XIAOMI_PLAYER_STATIC_LIBS "${XIAOMI_PLAYER_LIB_DIR}/libplayerc++.a"
    ${XIAOMI_PLAYER_STATIC_C}
)

# playerxdr in libplayerinterface.a uses Sun RPC XDR (libtirpc on Linux).
set(XIAOMI_PLAYER_UNIX_LIBS m z pthread)
if(UNIX)
  find_library(
    XIAOMI_PLAYER_TIRPC
    NAMES tirpc
  )
  if(XIAOMI_PLAYER_TIRPC)
    list(APPEND XIAOMI_PLAYER_UNIX_LIBS ${XIAOMI_PLAYER_TIRPC})
  else()
    message(
      WARNING
        "libtirpc not found (install libtirpc-dev). "
        "Linking Player clients will fail with undefined xdr_* references."
    )
  endif()
endif()

add_library(xiaomi_player_playercxx INTERFACE)
target_include_directories(
  xiaomi_player_playercxx
  INTERFACE "${XIAOMI_PLAYER_PREFIX}/include"
)
target_link_libraries(
  xiaomi_player_playercxx
  INTERFACE ${XIAOMI_PLAYER_STATIC_LIBS}
)
if(UNIX)
  target_link_libraries(
    xiaomi_player_playercxx
    INTERFACE ${XIAOMI_PLAYER_UNIX_LIBS}
  )
endif()

add_library(xiaomi_player_playerc INTERFACE)
target_include_directories(
  xiaomi_player_playerc
  INTERFACE "${XIAOMI_PLAYER_PREFIX}/include"
)
target_link_libraries(
  xiaomi_player_playerc
  INTERFACE ${XIAOMI_PLAYER_STATIC_C}
)
if(UNIX)
  target_link_libraries(
    xiaomi_player_playerc
    INTERFACE ${XIAOMI_PLAYER_UNIX_LIBS}
  )
endif()

add_library(xiaomi_player::playercxx ALIAS xiaomi_player_playercxx)
add_library(xiaomi_player::playerc ALIAS xiaomi_player_playerc)

add_dependencies(xiaomi_player_playercxx player-lib)
add_dependencies(xiaomi_player_playerc player-lib)

add_library(xiaomi_player_clients INTERFACE)
target_include_directories(
  xiaomi_player_clients
  INTERFACE "${XIAOMI_PLAYER_PREFIX}/include"
)
target_link_libraries(
  xiaomi_player_clients
  INTERFACE ${XIAOMI_PLAYER_STATIC_LIBS}
)
if(UNIX)
  target_link_libraries(
    xiaomi_player_clients
    INTERFACE ${XIAOMI_PLAYER_UNIX_LIBS}
  )
endif()
add_dependencies(xiaomi_player_clients player-lib)
add_library(xiaomi_player::clients ALIAS xiaomi_player_clients)
